-- SQL seed for service_areas and tradie_service_areas tables
-- Generated from nz-service-areas.json
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS service_areas (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  country TEXT NOT NULL DEFAULT 'New Zealand',
  city TEXT NOT NULL,
  area TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_service_areas_city_area ON service_areas(city, area);
CREATE INDEX IF NOT EXISTS idx_service_areas_city ON service_areas(city);

CREATE TABLE IF NOT EXISTS tradie_service_areas (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  tradie_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  service_area_id UUID NOT NULL REFERENCES service_areas(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_tradie_service_areas_unique ON tradie_service_areas(tradie_id, service_area_id);
CREATE INDEX IF NOT EXISTS idx_tradie_service_areas_service_area ON tradie_service_areas(service_area_id);

-- Data seed
INSERT INTO service_areas (country, city, area) VALUES
  ('New Zealand', 'Akaroa', 'Akaroa'),
  ('New Zealand', 'Alexandra', 'Alexandra'),
  ('New Zealand', 'Alexandra', 'Bridge Hill'),
  ('New Zealand', 'Alexandra', 'Letts Gully'),
  ('New Zealand', 'Algies Bay', 'Algies Bay'),
  ('New Zealand', 'Amberley', 'Amberley'),
  ('New Zealand', 'Arrowtown', 'Arrowtown'),
  ('New Zealand', 'Ashburton', 'Allenton'),
  ('New Zealand', 'Ashburton', 'Ashburton'),
  ('New Zealand', 'Ashburton', 'Elgin'),
  ('New Zealand', 'Ashburton', 'Hampstead'),
  ('New Zealand', 'Ashburton', 'Netherby'),
  ('New Zealand', 'Ashburton', 'Tinwald'),
  ('New Zealand', 'Ashhurst', 'Ashhurst'),
  ('New Zealand', 'Auckland', 'Albany'),
  ('New Zealand', 'Auckland', 'Albany Heights'),
  ('New Zealand', 'Auckland', 'Alfriston'),
  ('New Zealand', 'Auckland', 'Auckland Airport'),
  ('New Zealand', 'Auckland', 'Auckland Central'),
  ('New Zealand', 'Auckland', 'Avondale'),
  ('New Zealand', 'Auckland', 'Bayswater'),
  ('New Zealand', 'Auckland', 'Bayview'),
  ('New Zealand', 'Auckland', 'Beach Haven'),
  ('New Zealand', 'Auckland', 'Beachlands'),
  ('New Zealand', 'Auckland', 'Belmont'),
  ('New Zealand', 'Auckland', 'Birkdale'),
  ('New Zealand', 'Auckland', 'Birkenhead'),
  ('New Zealand', 'Auckland', 'Blockhouse Bay'),
  ('New Zealand', 'Auckland', 'Botany Downs'),
  ('New Zealand', 'Auckland', 'Browns Bay'),
  ('New Zealand', 'Auckland', 'Bucklands Beach'),
  ('New Zealand', 'Auckland', 'Burswood'),
  ('New Zealand', 'Auckland', 'Campbells Bay'),
  ('New Zealand', 'Auckland', 'Castor Bay'),
  ('New Zealand', 'Auckland', 'Chatswood'),
  ('New Zealand', 'Auckland', 'Clendon Park'),
  ('New Zealand', 'Auckland', 'Clover Park'),
  ('New Zealand', 'Auckland', 'Cockle Bay'),
  ('New Zealand', 'Auckland', 'Cornwallis'),
  ('New Zealand', 'Auckland', 'Dannemora'),
  ('New Zealand', 'Auckland', 'Devonport'),
  ('New Zealand', 'Auckland', 'East Tamaki'),
  ('New Zealand', 'Auckland', 'East Tamaki Heights'),
  ('New Zealand', 'Auckland', 'Eastern Beach'),
  ('New Zealand', 'Auckland', 'Eden Terrace'),
  ('New Zealand', 'Auckland', 'Ellerslie'),
  ('New Zealand', 'Auckland', 'Epsom'),
  ('New Zealand', 'Auckland', 'Fairview Heights'),
  ('New Zealand', 'Auckland', 'Farm Cove'),
  ('New Zealand', 'Auckland', 'Favona'),
  ('New Zealand', 'Auckland', 'Flat Bush'),
  ('New Zealand', 'Auckland', 'Forrest Hill'),
  ('New Zealand', 'Auckland', 'Freemans Bay'),
  ('New Zealand', 'Auckland', 'Glen Eden'),
  ('New Zealand', 'Auckland', 'Glen Innes'),
  ('New Zealand', 'Auckland', 'Glendene'),
  ('New Zealand', 'Auckland', 'Glendowie'),
  ('New Zealand', 'Auckland', 'Glenfield'),
  ('New Zealand', 'Auckland', 'Golflands'),
  ('New Zealand', 'Auckland', 'Goodwood Heights'),
  ('New Zealand', 'Auckland', 'Grafton'),
  ('New Zealand', 'Auckland', 'Green Bay'),
  ('New Zealand', 'Auckland', 'Greenhithe'),
  ('New Zealand', 'Auckland', 'Greenlane'),
  ('New Zealand', 'Auckland', 'Grey Lynn'),
  ('New Zealand', 'Auckland', 'Half Moon Bay'),
  ('New Zealand', 'Auckland', 'Hauraki'),
  ('New Zealand', 'Auckland', 'Henderson'),
  ('New Zealand', 'Auckland', 'Henderson Valley'),
  ('New Zealand', 'Auckland', 'Herald Island'),
  ('New Zealand', 'Auckland', 'Herne Bay'),
  ('New Zealand', 'Auckland', 'Highland Park'),
  ('New Zealand', 'Auckland', 'Hillcrest'),
  ('New Zealand', 'Auckland', 'Hillpark'),
  ('New Zealand', 'Auckland', 'Hillsborough'),
  ('New Zealand', 'Auckland', 'Hobsonville'),
  ('New Zealand', 'Auckland', 'Howick'),
  ('New Zealand', 'Auckland', 'Huia'),
  ('New Zealand', 'Auckland', 'Huntington Park'),
  ('New Zealand', 'Auckland', 'Kelston'),
  ('New Zealand', 'Auckland', 'Kingsland'),
  ('New Zealand', 'Auckland', 'Kohimarama'),
  ('New Zealand', 'Auckland', 'Laingholm'),
  ('New Zealand', 'Auckland', 'Long Bay'),
  ('New Zealand', 'Auckland', 'Lucas Heights'),
  ('New Zealand', 'Auckland', 'Lynfield'),
  ('New Zealand', 'Auckland', 'Mairangi Bay'),
  ('New Zealand', 'Auckland', 'Mangere'),
  ('New Zealand', 'Auckland', 'Mangere Bridge'),
  ('New Zealand', 'Auckland', 'Mangere East'),
  ('New Zealand', 'Auckland', 'Manukau'),
  ('New Zealand', 'Auckland', 'Manurewa'),
  ('New Zealand', 'Auckland', 'Manurewa East'),
  ('New Zealand', 'Auckland', 'Maraetai'),
  ('New Zealand', 'Auckland', 'Massey'),
  ('New Zealand', 'Auckland', 'Meadowbank'),
  ('New Zealand', 'Auckland', 'Mechanics Bay'),
  ('New Zealand', 'Auckland', 'Mellons Bay'),
  ('New Zealand', 'Auckland', 'Middlemore Hospital'),
  ('New Zealand', 'Auckland', 'Milford'),
  ('New Zealand', 'Auckland', 'Mission Bay'),
  ('New Zealand', 'Auckland', 'Morningside'),
  ('New Zealand', 'Auckland', 'Mount Albert'),
  ('New Zealand', 'Auckland', 'Mount Eden'),
  ('New Zealand', 'Auckland', 'Mount Roskill'),
  ('New Zealand', 'Auckland', 'Mount Wellington'),
  ('New Zealand', 'Auckland', 'Murrays Bay'),
  ('New Zealand', 'Auckland', 'Narrow Neck'),
  ('New Zealand', 'Auckland', 'New Lynn'),
  ('New Zealand', 'Auckland', 'New Windsor'),
  ('New Zealand', 'Auckland', 'Newmarket'),
  ('New Zealand', 'Auckland', 'Nihotupu'),
  ('New Zealand', 'Auckland', 'Northcote'),
  ('New Zealand', 'Auckland', 'Northcote Point'),
  ('New Zealand', 'Auckland', 'Northcross'),
  ('New Zealand', 'Auckland', 'Northpark'),
  ('New Zealand', 'Auckland', 'Okura'),
  ('New Zealand', 'Auckland', 'One Tree Hill'),
  ('New Zealand', 'Auckland', 'Onehunga'),
  ('New Zealand', 'Auckland', 'Orakei'),
  ('New Zealand', 'Auckland', 'Oratia'),
  ('New Zealand', 'Auckland', 'Otahuhu'),
  ('New Zealand', 'Auckland', 'Otara'),
  ('New Zealand', 'Auckland', 'Oteha'),
  ('New Zealand', 'Auckland', 'Pakuranga'),
  ('New Zealand', 'Auckland', 'Pakuranga Heights'),
  ('New Zealand', 'Auckland', 'Panmure'),
  ('New Zealand', 'Auckland', 'Papatoetoe'),
  ('New Zealand', 'Auckland', 'Parau'),
  ('New Zealand', 'Auckland', 'Paremoremo'),
  ('New Zealand', 'Auckland', 'Parnell'),
  ('New Zealand', 'Auckland', 'Penrose'),
  ('New Zealand', 'Auckland', 'Pinehill'),
  ('New Zealand', 'Auckland', 'Point Chevalier'),
  ('New Zealand', 'Auckland', 'Point England'),
  ('New Zealand', 'Auckland', 'Ponsonby'),
  ('New Zealand', 'Auckland', 'Randwick Park'),
  ('New Zealand', 'Auckland', 'Ranui'),
  ('New Zealand', 'Auckland', 'Redvale'),
  ('New Zealand', 'Auckland', 'Remuera'),
  ('New Zealand', 'Auckland', 'Rosedale'),
  ('New Zealand', 'Auckland', 'Rothesay Bay'),
  ('New Zealand', 'Auckland', 'Royal Oak'),
  ('New Zealand', 'Auckland', 'Saint Heliers'),
  ('New Zealand', 'Auckland', 'Saint Marys Bay'),
  ('New Zealand', 'Auckland', 'Sandringham'),
  ('New Zealand', 'Auckland', 'Schnapper Rock'),
  ('New Zealand', 'Auckland', 'Shamrock Park'),
  ('New Zealand', 'Auckland', 'Shelly Park'),
  ('New Zealand', 'Auckland', 'Somerville'),
  ('New Zealand', 'Auckland', 'St Johns'),
  ('New Zealand', 'Auckland', 'Stanley Point'),
  ('New Zealand', 'Auckland', 'Stonefields'),
  ('New Zealand', 'Auckland', 'Sunnyhills'),
  ('New Zealand', 'Auckland', 'Sunnynook'),
  ('New Zealand', 'Auckland', 'Sunnyvale'),
  ('New Zealand', 'Auckland', 'Swanson'),
  ('New Zealand', 'Auckland', 'Takanini'),
  ('New Zealand', 'Auckland', 'Takapuna'),
  ('New Zealand', 'Auckland', 'Te Atatu Peninsula'),
  ('New Zealand', 'Auckland', 'Te Atatu South'),
  ('New Zealand', 'Auckland', 'The Gardens'),
  ('New Zealand', 'Auckland', 'Three Kings'),
  ('New Zealand', 'Auckland', 'Titirangi'),
  ('New Zealand', 'Auckland', 'Torbay'),
  ('New Zealand', 'Auckland', 'Totara Heights'),
  ('New Zealand', 'Auckland', 'Totara Park'),
  ('New Zealand', 'Auckland', 'Totara Vale'),
  ('New Zealand', 'Auckland', 'Unsworth Heights'),
  ('New Zealand', 'Auckland', 'Wai o Taiki Bay'),
  ('New Zealand', 'Auckland', 'Waiake'),
  ('New Zealand', 'Auckland', 'Waiatarua'),
  ('New Zealand', 'Auckland', 'Wairau Valley'),
  ('New Zealand', 'Auckland', 'Waitakere'),
  ('New Zealand', 'Auckland', 'Waterview'),
  ('New Zealand', 'Auckland', 'Wattle Downs'),
  ('New Zealand', 'Auckland', 'Wesley'),
  ('New Zealand', 'Auckland', 'West Harbour'),
  ('New Zealand', 'Auckland', 'Western Springs'),
  ('New Zealand', 'Auckland', 'Westgate'),
  ('New Zealand', 'Auckland', 'Westhaven'),
  ('New Zealand', 'Auckland', 'Westmere'),
  ('New Zealand', 'Auckland', 'Weymouth'),
  ('New Zealand', 'Auckland', 'Whenuapai'),
  ('New Zealand', 'Auckland', 'Windsor Park'),
  ('New Zealand', 'Auckland', 'Wiri'),
  ('New Zealand', 'Balclutha', 'Balclutha'),
  ('New Zealand', 'Big Omaha', 'Big Omaha'),
  ('New Zealand', 'Blenheim', 'Blenheim'),
  ('New Zealand', 'Blenheim', 'Burleigh'),
  ('New Zealand', 'Blenheim', 'Grovetown'),
  ('New Zealand', 'Blenheim', 'Islington'),
  ('New Zealand', 'Blenheim', 'Mayfield'),
  ('New Zealand', 'Blenheim', 'Redwoodtown'),
  ('New Zealand', 'Blenheim', 'Riversdale'),
  ('New Zealand', 'Blenheim', 'Springlands'),
  ('New Zealand', 'Blenheim', 'Taylor Pass'),
  ('New Zealand', 'Blenheim', 'Wither Hills'),
  ('New Zealand', 'Blenheim', 'Witherlea'),
  ('New Zealand', 'Blenheim', 'Woodbourne')
ON CONFLICT (city, area) DO NOTHING;

INSERT INTO service_areas (country, city, area) VALUES
  ('New Zealand', 'Blenheim', 'Yelverton'),
  ('New Zealand', 'Bluff', 'Bluff'),
  ('New Zealand', 'Bluff', 'Ocean Beach'),
  ('New Zealand', 'Brightwater', 'Brightwater'),
  ('New Zealand', 'Bulls', 'Bulls'),
  ('New Zealand', 'Bulls', 'Ohakea'),
  ('New Zealand', 'Burnham', 'Burnham'),
  ('New Zealand', 'Cable Bay', 'Cable Bay'),
  ('New Zealand', 'Cambridge', 'Cambridge'),
  ('New Zealand', 'Cambridge', 'Leamington'),
  ('New Zealand', 'Carterton', 'Carterton'),
  ('New Zealand', 'Carterton', 'Clareville'),
  ('New Zealand', 'Cheviot', 'Cheviot'),
  ('New Zealand', 'Christchurch', 'Addington'),
  ('New Zealand', 'Christchurch', 'Aidanfield'),
  ('New Zealand', 'Christchurch', 'Aranui'),
  ('New Zealand', 'Christchurch', 'Avondale'),
  ('New Zealand', 'Christchurch', 'Avonhead'),
  ('New Zealand', 'Christchurch', 'Avonside'),
  ('New Zealand', 'Christchurch', 'Beckenham'),
  ('New Zealand', 'Christchurch', 'Belfast'),
  ('New Zealand', 'Christchurch', 'Bexley'),
  ('New Zealand', 'Christchurch', 'Bishopdale'),
  ('New Zealand', 'Christchurch', 'Bottle Lake'),
  ('New Zealand', 'Christchurch', 'Bromley'),
  ('New Zealand', 'Christchurch', 'Brooklands'),
  ('New Zealand', 'Christchurch', 'Broomfield'),
  ('New Zealand', 'Christchurch', 'Bryndwr'),
  ('New Zealand', 'Christchurch', 'Burnside'),
  ('New Zealand', 'Christchurch', 'Burwood'),
  ('New Zealand', 'Christchurch', 'Casebrook'),
  ('New Zealand', 'Christchurch', 'Cashmere'),
  ('New Zealand', 'Christchurch', 'Christchurch Airport'),
  ('New Zealand', 'Christchurch', 'Christchurch Central'),
  ('New Zealand', 'Christchurch', 'Clifton'),
  ('New Zealand', 'Christchurch', 'Coutts Island'),
  ('New Zealand', 'Christchurch', 'Cracroft'),
  ('New Zealand', 'Christchurch', 'Dallington'),
  ('New Zealand', 'Christchurch', 'Edgeware'),
  ('New Zealand', 'Christchurch', 'Fendalton'),
  ('New Zealand', 'Christchurch', 'Ferrymead'),
  ('New Zealand', 'Christchurch', 'Halswell'),
  ('New Zealand', 'Christchurch', 'Harewood'),
  ('New Zealand', 'Christchurch', 'Heathcote Valley'),
  ('New Zealand', 'Christchurch', 'Hei Hei'),
  ('New Zealand', 'Christchurch', 'Hillmorton'),
  ('New Zealand', 'Christchurch', 'Hillsborough'),
  ('New Zealand', 'Christchurch', 'Hoon Hay'),
  ('New Zealand', 'Christchurch', 'Hornby'),
  ('New Zealand', 'Christchurch', 'Hornby South'),
  ('New Zealand', 'Christchurch', 'Huntsbury'),
  ('New Zealand', 'Christchurch', 'Ilam'),
  ('New Zealand', 'Christchurch', 'Islington'),
  ('New Zealand', 'Christchurch', 'Kainga'),
  ('New Zealand', 'Christchurch', 'Kennedys Bush'),
  ('New Zealand', 'Christchurch', 'Linwood'),
  ('New Zealand', 'Christchurch', 'Mairehau'),
  ('New Zealand', 'Christchurch', 'Marshland'),
  ('New Zealand', 'Christchurch', 'McLeans Island'),
  ('New Zealand', 'Christchurch', 'Merivale'),
  ('New Zealand', 'Christchurch', 'Middleton'),
  ('New Zealand', 'Christchurch', 'Moncks Bay'),
  ('New Zealand', 'Christchurch', 'Mount Pleasant'),
  ('New Zealand', 'Christchurch', 'New Brighton'),
  ('New Zealand', 'Christchurch', 'North New Brighton'),
  ('New Zealand', 'Christchurch', 'Northcote'),
  ('New Zealand', 'Christchurch', 'Northwood'),
  ('New Zealand', 'Christchurch', 'Opawa'),
  ('New Zealand', 'Christchurch', 'Ouruhia'),
  ('New Zealand', 'Christchurch', 'Papanui'),
  ('New Zealand', 'Christchurch', 'Parklands'),
  ('New Zealand', 'Christchurch', 'Phillipstown'),
  ('New Zealand', 'Christchurch', 'Redcliffs'),
  ('New Zealand', 'Christchurch', 'Redwood'),
  ('New Zealand', 'Christchurch', 'Riccarton'),
  ('New Zealand', 'Christchurch', 'Richmond'),
  ('New Zealand', 'Christchurch', 'Richmond Hill'),
  ('New Zealand', 'Christchurch', 'Russley'),
  ('New Zealand', 'Christchurch', 'Saint Martins'),
  ('New Zealand', 'Christchurch', 'Scarborough'),
  ('New Zealand', 'Christchurch', 'Shirley'),
  ('New Zealand', 'Christchurch', 'Sockburn'),
  ('New Zealand', 'Christchurch', 'Somerfield'),
  ('New Zealand', 'Christchurch', 'South New Brighton'),
  ('New Zealand', 'Christchurch', 'Southshore'),
  ('New Zealand', 'Christchurch', 'Spencerville'),
  ('New Zealand', 'Christchurch', 'Spreydon'),
  ('New Zealand', 'Christchurch', 'St Albans'),
  ('New Zealand', 'Christchurch', 'Strowan'),
  ('New Zealand', 'Christchurch', 'Sumner'),
  ('New Zealand', 'Christchurch', 'Sydenham'),
  ('New Zealand', 'Christchurch', 'Te Onepoto / Taylors Mistake'),
  ('New Zealand', 'Christchurch', 'Templeton'),
  ('New Zealand', 'Christchurch', 'Upper Riccarton'),
  ('New Zealand', 'Christchurch', 'Waimairi Beach'),
  ('New Zealand', 'Christchurch', 'Wainoni'),
  ('New Zealand', 'Christchurch', 'Waltham'),
  ('New Zealand', 'Christchurch', 'Westmorland'),
  ('New Zealand', 'Christchurch', 'Wigram'),
  ('New Zealand', 'Christchurch', 'Woolston'),
  ('New Zealand', 'Christchurch', 'Yaldhurst'),
  ('New Zealand', 'Clarks Beach', 'Clarks Beach'),
  ('New Zealand', 'Clinton', 'Clinton'),
  ('New Zealand', 'Clive', 'Clive'),
  ('New Zealand', 'Clyde', 'Clyde'),
  ('New Zealand', 'Coopers Beach', 'Coopers Beach'),
  ('New Zealand', 'Coromandel', 'Coromandel'),
  ('New Zealand', 'Coromandel', 'Preece Point'),
  ('New Zealand', 'Coromandel', 'Te Rerenga'),
  ('New Zealand', 'Cromwell', 'Cromwell'),
  ('New Zealand', 'Dannevirke', 'Dannevirke'),
  ('New Zealand', 'Darfield', 'Darfield'),
  ('New Zealand', 'Dargaville', 'Dargaville'),
  ('New Zealand', 'Doyleston', 'Doyleston'),
  ('New Zealand', 'Drury', 'Drury'),
  ('New Zealand', 'Dunedin', 'Abbotsford'),
  ('New Zealand', 'Dunedin', 'Andersons Bay'),
  ('New Zealand', 'Dunedin', 'Balaclava'),
  ('New Zealand', 'Dunedin', 'Belleknowes'),
  ('New Zealand', 'Dunedin', 'Blackhead'),
  ('New Zealand', 'Dunedin', 'Bradford'),
  ('New Zealand', 'Dunedin', 'Brighton'),
  ('New Zealand', 'Dunedin', 'Broad Bay'),
  ('New Zealand', 'Dunedin', 'Brockville'),
  ('New Zealand', 'Dunedin', 'Burnside'),
  ('New Zealand', 'Dunedin', 'Calton Hill'),
  ('New Zealand', 'Dunedin', 'Careys Bay'),
  ('New Zealand', 'Dunedin', 'Caversham'),
  ('New Zealand', 'Dunedin', 'Chain Hills'),
  ('New Zealand', 'Dunedin', 'Clyde Hill'),
  ('New Zealand', 'Dunedin', 'Company Bay'),
  ('New Zealand', 'Dunedin', 'Concord'),
  ('New Zealand', 'Dunedin', 'Corstorphine'),
  ('New Zealand', 'Dunedin', 'Dalmore'),
  ('New Zealand', 'Dunedin', 'Dunedin Central'),
  ('New Zealand', 'Dunedin', 'Fairfield'),
  ('New Zealand', 'Dunedin', 'Forbury'),
  ('New Zealand', 'Dunedin', 'Glenleith'),
  ('New Zealand', 'Dunedin', 'Glenross'),
  ('New Zealand', 'Dunedin', 'Green Island'),
  ('New Zealand', 'Dunedin', 'Halfway Bush'),
  ('New Zealand', 'Dunedin', 'Helensburgh'),
  ('New Zealand', 'Dunedin', 'Highcliff'),
  ('New Zealand', 'Dunedin', 'Kaikorai'),
  ('New Zealand', 'Dunedin', 'Kenmure'),
  ('New Zealand', 'Dunedin', 'Kensington'),
  ('New Zealand', 'Dunedin', 'Kew'),
  ('New Zealand', 'Dunedin', 'Larnachs Castle'),
  ('New Zealand', 'Dunedin', 'Lawyers Head'),
  ('New Zealand', 'Dunedin', 'Leith Valley'),
  ('New Zealand', 'Dunedin', 'Liberton'),
  ('New Zealand', 'Dunedin', 'Lookout Point'),
  ('New Zealand', 'Dunedin', 'Macandrew Bay'),
  ('New Zealand', 'Dunedin', 'Maia'),
  ('New Zealand', 'Dunedin', 'Maori Hill'),
  ('New Zealand', 'Dunedin', 'Maryhill'),
  ('New Zealand', 'Dunedin', 'Mornington'),
  ('New Zealand', 'Dunedin', 'Mount Grand'),
  ('New Zealand', 'Dunedin', 'Musselburgh'),
  ('New Zealand', 'Dunedin', 'Normanby'),
  ('New Zealand', 'Dunedin', 'North Dunedin'),
  ('New Zealand', 'Dunedin', 'North East Valley'),
  ('New Zealand', 'Dunedin', 'Ocean Grove'),
  ('New Zealand', 'Dunedin', 'Ocean View'),
  ('New Zealand', 'Dunedin', 'Opoho'),
  ('New Zealand', 'Dunedin', 'Pine Hill'),
  ('New Zealand', 'Dunedin', 'Port Chalmers'),
  ('New Zealand', 'Dunedin', 'Portobello'),
  ('New Zealand', 'Dunedin', 'Ravensbourne'),
  ('New Zealand', 'Dunedin', 'Roseneath'),
  ('New Zealand', 'Dunedin', 'Roslyn'),
  ('New Zealand', 'Dunedin', 'Saddle Hill'),
  ('New Zealand', 'Dunedin', 'Saint Clair'),
  ('New Zealand', 'Dunedin', 'Saint Kilda'),
  ('New Zealand', 'Dunedin', 'Saint Leonards'),
  ('New Zealand', 'Dunedin', 'Sawyers Bay'),
  ('New Zealand', 'Dunedin', 'Scroggs Hill'),
  ('New Zealand', 'Dunedin', 'Shiel Hill'),
  ('New Zealand', 'Dunedin', 'South Dunedin'),
  ('New Zealand', 'Dunedin', 'Tainui'),
  ('New Zealand', 'Dunedin', 'The Cove'),
  ('New Zealand', 'Dunedin', 'The Glen'),
  ('New Zealand', 'Dunedin', 'Upper Junction'),
  ('New Zealand', 'Dunedin', 'Vauxhall'),
  ('New Zealand', 'Dunedin', 'Wakari'),
  ('New Zealand', 'Dunedin', 'Waldronville'),
  ('New Zealand', 'Dunedin', 'Waverley'),
  ('New Zealand', 'Dunedin', 'Westwood'),
  ('New Zealand', 'Dunedin', 'Woodhaugh'),
  ('New Zealand', 'Edendale', 'Edendale'),
  ('New Zealand', 'Edgecumbe', 'Edgecumbe'),
  ('New Zealand', 'EketÄhuna', 'Eketahuna'),
  ('New Zealand', 'Eltham', 'Eltham'),
  ('New Zealand', 'Fairlie', 'Fairlie'),
  ('New Zealand', 'Featherston', 'Featherston'),
  ('New Zealand', 'Feilding', 'Feilding'),
  ('New Zealand', 'Foxton', 'Foxton'),
  ('New Zealand', 'Foxton', 'Foxton Beach'),
  ('New Zealand', 'Geraldine', 'Geraldine'),
  ('New Zealand', 'Gisborne', 'Awapuni')
ON CONFLICT (city, area) DO NOTHING;

INSERT INTO service_areas (country, city, area) VALUES
  ('New Zealand', 'Gisborne', 'Elgin'),
  ('New Zealand', 'Gisborne', 'Gisborne'),
  ('New Zealand', 'Gisborne', 'Gisborne Airport'),
  ('New Zealand', 'Gisborne', 'Inner Kaiti'),
  ('New Zealand', 'Gisborne', 'Kaiti'),
  ('New Zealand', 'Gisborne', 'Lytton West'),
  ('New Zealand', 'Gisborne', 'Makaraka'),
  ('New Zealand', 'Gisborne', 'Makauri'),
  ('New Zealand', 'Gisborne', 'Mangapapa'),
  ('New Zealand', 'Gisborne', 'Matawhero'),
  ('New Zealand', 'Gisborne', 'Okitu'),
  ('New Zealand', 'Gisborne', 'Outer Kaiti'),
  ('New Zealand', 'Gisborne', 'Patutahi'),
  ('New Zealand', 'Gisborne', 'Riverdale'),
  ('New Zealand', 'Gisborne', 'Tamarau'),
  ('New Zealand', 'Gisborne', 'Te Hapara'),
  ('New Zealand', 'Gisborne', 'Waerengaahika'),
  ('New Zealand', 'Gisborne', 'Waihirere'),
  ('New Zealand', 'Gisborne', 'Wainui'),
  ('New Zealand', 'Gisborne', 'Waituhi'),
  ('New Zealand', 'Gisborne', 'Whataupoko'),
  ('New Zealand', 'Gore', 'Charlton'),
  ('New Zealand', 'Gore', 'East Gore'),
  ('New Zealand', 'Gore', 'Gore'),
  ('New Zealand', 'Granity', 'Granity'),
  ('New Zealand', 'Greymouth', 'Blackball'),
  ('New Zealand', 'Greymouth', 'Blaketown'),
  ('New Zealand', 'Greymouth', 'Camerons'),
  ('New Zealand', 'Greymouth', 'Coal Creek'),
  ('New Zealand', 'Greymouth', 'Cobden'),
  ('New Zealand', 'Greymouth', 'Dillmanstown'),
  ('New Zealand', 'Greymouth', 'Dobson'),
  ('New Zealand', 'Greymouth', 'Gladstone'),
  ('New Zealand', 'Greymouth', 'Greymouth'),
  ('New Zealand', 'Greymouth', 'Kaiata'),
  ('New Zealand', 'Greymouth', 'Karoro'),
  ('New Zealand', 'Greymouth', 'Kumara'),
  ('New Zealand', 'Greymouth', 'Kumara Junction'),
  ('New Zealand', 'Greymouth', 'Marsden'),
  ('New Zealand', 'Greymouth', 'Nine Mile'),
  ('New Zealand', 'Greymouth', 'Paroa'),
  ('New Zealand', 'Greymouth', 'Point Elizabeth'),
  ('New Zealand', 'Greymouth', 'Rapahoe'),
  ('New Zealand', 'Greymouth', 'Rutherglen'),
  ('New Zealand', 'Greymouth', 'Stillwater'),
  ('New Zealand', 'Greymouth', 'Taylorville'),
  ('New Zealand', 'Greytown', 'Greytown'),
  ('New Zealand', 'Hamilton', 'Avalon'),
  ('New Zealand', 'Hamilton', 'Bader'),
  ('New Zealand', 'Hamilton', 'Beerescourt'),
  ('New Zealand', 'Hamilton', 'Chartwell'),
  ('New Zealand', 'Hamilton', 'Chedworth'),
  ('New Zealand', 'Hamilton', 'Claudelands'),
  ('New Zealand', 'Hamilton', 'Deanwell'),
  ('New Zealand', 'Hamilton', 'Dinsdale'),
  ('New Zealand', 'Hamilton', 'Enderley'),
  ('New Zealand', 'Hamilton', 'Fairfield'),
  ('New Zealand', 'Hamilton', 'Fairview Downs'),
  ('New Zealand', 'Hamilton', 'Fitzroy'),
  ('New Zealand', 'Hamilton', 'Flagstaff'),
  ('New Zealand', 'Hamilton', 'Forest Lake'),
  ('New Zealand', 'Hamilton', 'Frankton'),
  ('New Zealand', 'Hamilton', 'Glenview'),
  ('New Zealand', 'Hamilton', 'Grandview Heights'),
  ('New Zealand', 'Hamilton', 'Hamilton Central'),
  ('New Zealand', 'Hamilton', 'Hamilton East'),
  ('New Zealand', 'Hamilton', 'Hamilton Lake'),
  ('New Zealand', 'Hamilton', 'Harrowfield'),
  ('New Zealand', 'Hamilton', 'Hillcrest'),
  ('New Zealand', 'Hamilton', 'Huntington'),
  ('New Zealand', 'Hamilton', 'Maeroa'),
  ('New Zealand', 'Hamilton', 'Melville'),
  ('New Zealand', 'Hamilton', 'Nawton'),
  ('New Zealand', 'Hamilton', 'Northgate'),
  ('New Zealand', 'Hamilton', 'Peacocke'),
  ('New Zealand', 'Hamilton', 'Pukete'),
  ('New Zealand', 'Hamilton', 'Queenwood'),
  ('New Zealand', 'Hamilton', 'Riverlea'),
  ('New Zealand', 'Hamilton', 'Rotokauri'),
  ('New Zealand', 'Hamilton', 'Rototuna'),
  ('New Zealand', 'Hamilton', 'Rototuna North'),
  ('New Zealand', 'Hamilton', 'Ruakura'),
  ('New Zealand', 'Hamilton', 'Silverdale'),
  ('New Zealand', 'Hamilton', 'St Andrews'),
  ('New Zealand', 'Hamilton', 'Tauwhare'),
  ('New Zealand', 'Hamilton', 'Te Rapa'),
  ('New Zealand', 'Hamilton', 'Te Rapa Park'),
  ('New Zealand', 'Hamilton', 'Temple View'),
  ('New Zealand', 'Hamilton', 'Waikato Hospital'),
  ('New Zealand', 'Hamilton', 'Western Heights'),
  ('New Zealand', 'Hamilton', 'Whitiora'),
  ('New Zealand', 'Hampden', 'Hampden'),
  ('New Zealand', 'Hanmer Springs', 'Hanmer Forest'),
  ('New Zealand', 'Hanmer Springs', 'Hanmer Springs'),
  ('New Zealand', 'Hastings', 'Akina'),
  ('New Zealand', 'Hastings', 'Camberley'),
  ('New Zealand', 'Hastings', 'Flaxmere'),
  ('New Zealand', 'Hastings', 'Frimley'),
  ('New Zealand', 'Hastings', 'Hastings'),
  ('New Zealand', 'Hastings', 'Longlands'),
  ('New Zealand', 'Hastings', 'Mahora'),
  ('New Zealand', 'Hastings', 'Mayfair'),
  ('New Zealand', 'Hastings', 'Parkvale'),
  ('New Zealand', 'Hastings', 'Raureka'),
  ('New Zealand', 'Hastings', 'Saint Leonards'),
  ('New Zealand', 'Hastings', 'Tomoana'),
  ('New Zealand', 'Hastings', 'Woolwich'),
  ('New Zealand', 'Haumoana', 'Haumoana'),
  ('New Zealand', 'Havelock', 'Havelock'),
  ('New Zealand', 'Havelock North', 'Havelock North'),
  ('New Zealand', 'Hector', 'Hector'),
  ('New Zealand', 'Hector', 'Ngakawau'),
  ('New Zealand', 'Helensville', 'Helensville'),
  ('New Zealand', 'Helensville', 'Parakai'),
  ('New Zealand', 'Hikurangi', 'Glenbervie Forest'),
  ('New Zealand', 'Hikurangi', 'Hikurangi'),
  ('New Zealand', 'Hokitika', 'Blue Spur'),
  ('New Zealand', 'Hokitika', 'Hokitika'),
  ('New Zealand', 'Hokitika', 'Kaniere'),
  ('New Zealand', 'Huntly', 'Huntly'),
  ('New Zealand', 'HÄwera', 'Hawera'),
  ('New Zealand', 'HÄwera', 'Normanby'),
  ('New Zealand', 'Inglewood', 'Inglewood'),
  ('New Zealand', 'Invercargill', 'Appleby'),
  ('New Zealand', 'Invercargill', 'Ascot'),
  ('New Zealand', 'Invercargill', 'Avenal'),
  ('New Zealand', 'Invercargill', 'Clifton'),
  ('New Zealand', 'Invercargill', 'Georgetown'),
  ('New Zealand', 'Invercargill', 'Gladstone'),
  ('New Zealand', 'Invercargill', 'Glengarry'),
  ('New Zealand', 'Invercargill', 'Grasmere'),
  ('New Zealand', 'Invercargill', 'Hargest'),
  ('New Zealand', 'Invercargill', 'Hawthorndale'),
  ('New Zealand', 'Invercargill', 'Heidelberg'),
  ('New Zealand', 'Invercargill', 'Invercargill'),
  ('New Zealand', 'Invercargill', 'Kew'),
  ('New Zealand', 'Invercargill', 'Kingswell'),
  ('New Zealand', 'Invercargill', 'Lorneville'),
  ('New Zealand', 'Invercargill', 'Motu Rimu'),
  ('New Zealand', 'Invercargill', 'Newfield'),
  ('New Zealand', 'Invercargill', 'Prestonville'),
  ('New Zealand', 'Invercargill', 'Queens Park'),
  ('New Zealand', 'Invercargill', 'Richmond'),
  ('New Zealand', 'Invercargill', 'Rockdale'),
  ('New Zealand', 'Invercargill', 'Rosedale'),
  ('New Zealand', 'Invercargill', 'Seaward Bush'),
  ('New Zealand', 'Invercargill', 'Strathern'),
  ('New Zealand', 'Invercargill', 'Tisbury'),
  ('New Zealand', 'Invercargill', 'Turnbull Thomson Park'),
  ('New Zealand', 'Invercargill', 'Waihopai'),
  ('New Zealand', 'Invercargill', 'Waikiwi'),
  ('New Zealand', 'Invercargill', 'Waverley'),
  ('New Zealand', 'Invercargill', 'West Invercargill'),
  ('New Zealand', 'Invercargill', 'Windsor'),
  ('New Zealand', 'Invercargill', 'Woodend'),
  ('New Zealand', 'Kaiapoi', 'Kaiapoi'),
  ('New Zealand', 'Kaikohe', 'Kaikohe'),
  ('New Zealand', 'KaikÅura', 'Kaikoura'),
  ('New Zealand', 'KaikÅura', 'Kaikoura Flat'),
  ('New Zealand', 'KaikÅura', 'Kaikoura Peninsula'),
  ('New Zealand', 'KaikÅura', 'South Bay'),
  ('New Zealand', 'Kairaki', 'Kairaki'),
  ('New Zealand', 'Kaitaia', 'Ahipara'),
  ('New Zealand', 'Kaitaia', 'Kaitaia'),
  ('New Zealand', 'Kaitangata', 'Kaitangata'),
  ('New Zealand', 'Karangahake', 'Karangahake'),
  ('New Zealand', 'Katikati', 'Katikati'),
  ('New Zealand', 'Kawakawa', 'Kawakawa'),
  ('New Zealand', 'Kawakawa', 'Waiomio'),
  ('New Zealand', 'Kawerau', 'Kawerau'),
  ('New Zealand', 'Kerikeri', 'Kerikeri'),
  ('New Zealand', 'Kirwee', 'Kirwee'),
  ('New Zealand', 'KumeÅ«', 'Huapai'),
  ('New Zealand', 'KumeÅ«', 'Kumeu'),
  ('New Zealand', 'Kurow', 'Hakataramea'),
  ('New Zealand', 'Kurow', 'Kurow'),
  ('New Zealand', 'Lansdowne', 'Lansdowne'),
  ('New Zealand', 'Lawrence', 'Lawrence'),
  ('New Zealand', 'Leeston', 'Leeston'),
  ('New Zealand', 'Levin', 'Levin'),
  ('New Zealand', 'Levin', 'Poroutawhao'),
  ('New Zealand', 'Levin', 'Waitarere'),
  ('New Zealand', 'Levin', 'Waitarere Beach'),
  ('New Zealand', 'Lincoln', 'Lincoln'),
  ('New Zealand', 'Lower Hutt', 'Alicetown'),
  ('New Zealand', 'Lower Hutt', 'Avalon'),
  ('New Zealand', 'Lower Hutt', 'Belmont'),
  ('New Zealand', 'Lower Hutt', 'Boulcott'),
  ('New Zealand', 'Lower Hutt', 'Days Bay'),
  ('New Zealand', 'Lower Hutt', 'Eastbourne'),
  ('New Zealand', 'Lower Hutt', 'Epuni'),
  ('New Zealand', 'Lower Hutt', 'Fairfield'),
  ('New Zealand', 'Lower Hutt', 'Gracefield'),
  ('New Zealand', 'Lower Hutt', 'Harbour View'),
  ('New Zealand', 'Lower Hutt', 'Haywards'),
  ('New Zealand', 'Lower Hutt', 'Hutt Central'),
  ('New Zealand', 'Lower Hutt', 'Kelson'),
  ('New Zealand', 'Lower Hutt', 'Korokoro'),
  ('New Zealand', 'Lower Hutt', 'Lowry Bay'),
  ('New Zealand', 'Lower Hutt', 'Mahina Bay')
ON CONFLICT (city, area) DO NOTHING;

INSERT INTO service_areas (country, city, area) VALUES
  ('New Zealand', 'Lower Hutt', 'Manor Park'),
  ('New Zealand', 'Lower Hutt', 'Maungaraki'),
  ('New Zealand', 'Lower Hutt', 'Melling'),
  ('New Zealand', 'Lower Hutt', 'Moera'),
  ('New Zealand', 'Lower Hutt', 'Naenae'),
  ('New Zealand', 'Lower Hutt', 'Normandale'),
  ('New Zealand', 'Lower Hutt', 'Pencarrow Head'),
  ('New Zealand', 'Lower Hutt', 'Petone'),
  ('New Zealand', 'Lower Hutt', 'Point Howard'),
  ('New Zealand', 'Lower Hutt', 'Seaview'),
  ('New Zealand', 'Lower Hutt', 'Sorrento Bay'),
  ('New Zealand', 'Lower Hutt', 'Stokes Valley'),
  ('New Zealand', 'Lower Hutt', 'Sunshine Bay'),
  ('New Zealand', 'Lower Hutt', 'Taita'),
  ('New Zealand', 'Lower Hutt', 'Tirohanga'),
  ('New Zealand', 'Lower Hutt', 'Wainuiomata'),
  ('New Zealand', 'Lower Hutt', 'Waiwhetu'),
  ('New Zealand', 'Lower Hutt', 'Waterloo'),
  ('New Zealand', 'Lower Hutt', 'Woburn'),
  ('New Zealand', 'Lower Hutt', 'York Bay'),
  ('New Zealand', 'Lumsden', 'Lumsden'),
  ('New Zealand', 'Lyttelton', 'Cass Bay'),
  ('New Zealand', 'Lyttelton', 'Corsair Bay'),
  ('New Zealand', 'Lyttelton', 'Lyttelton'),
  ('New Zealand', 'Mamaku', 'Mamaku'),
  ('New Zealand', 'Manaia', 'Manaia'),
  ('New Zealand', 'Mangakino', 'Mangakino'),
  ('New Zealand', 'Mangawhai', 'Mangawhai'),
  ('New Zealand', 'Mangawhai', 'Mangawhai Heads'),
  ('New Zealand', 'MangÅnui', 'Mangonui'),
  ('New Zealand', 'Marlborough Sounds', 'Raetihi'),
  ('New Zealand', 'Martinborough', 'Martinborough'),
  ('New Zealand', 'Marton', 'Crofton'),
  ('New Zealand', 'Marton', 'Marton'),
  ('New Zealand', 'Masterton', 'Homebush'),
  ('New Zealand', 'Masterton', 'Kuripuni'),
  ('New Zealand', 'Masterton', 'Lansdowne'),
  ('New Zealand', 'Masterton', 'Masterton'),
  ('New Zealand', 'Masterton', 'Solway'),
  ('New Zealand', 'Masterton', 'Te Ore Ore'),
  ('New Zealand', 'Matamata', 'Matamata'),
  ('New Zealand', 'Mataura', 'Mataura'),
  ('New Zealand', 'Maungaturoto', 'Maungaturoto'),
  ('New Zealand', 'Methven', 'Methven'),
  ('New Zealand', 'Milford Sound', 'Milford Sound'),
  ('New Zealand', 'Milton', 'Milton'),
  ('New Zealand', 'Moerewa', 'Moerewa'),
  ('New Zealand', 'Morrinsville', 'Morrinsville'),
  ('New Zealand', 'Mosgiel', 'East Taieri'),
  ('New Zealand', 'Mosgiel', 'Kinmont Park'),
  ('New Zealand', 'Mosgiel', 'Mosgiel'),
  ('New Zealand', 'Motueka', 'Motueka'),
  ('New Zealand', 'Mount Maunganui', 'Mount Maunganui'),
  ('New Zealand', 'Mount Pleasant', 'Mount Pleasant'),
  ('New Zealand', 'Murchison', 'Murchison'),
  ('New Zealand', 'Murupara', 'Murupara'),
  ('New Zealand', 'MÄkara Beach', 'Makara Beach'),
  ('New Zealand', 'MÄpua', 'Mapua'),
  ('New Zealand', 'MÄpua', 'Ruby Bay'),
  ('New Zealand', 'Napier', 'Ahuriri'),
  ('New Zealand', 'Napier', 'Awatoto'),
  ('New Zealand', 'Napier', 'Bay View'),
  ('New Zealand', 'Napier', 'Bluff Hill'),
  ('New Zealand', 'Napier', 'Greenmeadows'),
  ('New Zealand', 'Napier', 'Hospital Hill'),
  ('New Zealand', 'Napier', 'Jervoistown'),
  ('New Zealand', 'Napier', 'Maraenui'),
  ('New Zealand', 'Napier', 'Marewa'),
  ('New Zealand', 'Napier', 'Meeanee'),
  ('New Zealand', 'Napier', 'Napier Airport'),
  ('New Zealand', 'Napier', 'Napier Port'),
  ('New Zealand', 'Napier', 'Napier South'),
  ('New Zealand', 'Napier', 'Onekawa'),
  ('New Zealand', 'Napier', 'Pandora'),
  ('New Zealand', 'Napier', 'Pirimai'),
  ('New Zealand', 'Napier', 'Poraiti'),
  ('New Zealand', 'Napier', 'Tamatea'),
  ('New Zealand', 'Napier', 'Taradale'),
  ('New Zealand', 'Napier', 'Te Awa'),
  ('New Zealand', 'Napier', 'Westshore'),
  ('New Zealand', 'Nelson', 'Annesbrook'),
  ('New Zealand', 'Nelson', 'Atawhai'),
  ('New Zealand', 'Nelson', 'Beachville'),
  ('New Zealand', 'Nelson', 'Bishopdale'),
  ('New Zealand', 'Nelson', 'Britannia Heights'),
  ('New Zealand', 'Nelson', 'Enner Glynn'),
  ('New Zealand', 'Nelson', 'Maitai'),
  ('New Zealand', 'Nelson', 'Marybank'),
  ('New Zealand', 'Nelson', 'Moana'),
  ('New Zealand', 'Nelson', 'Monaco'),
  ('New Zealand', 'Nelson', 'Nelson'),
  ('New Zealand', 'Nelson', 'Nelson Airport'),
  ('New Zealand', 'Nelson', 'Nelson South'),
  ('New Zealand', 'Nelson', 'Port Nelson'),
  ('New Zealand', 'Nelson', 'Stepneyville'),
  ('New Zealand', 'Nelson', 'Stoke'),
  ('New Zealand', 'Nelson', 'Tahunanui'),
  ('New Zealand', 'Nelson', 'The Brook'),
  ('New Zealand', 'Nelson', 'The Wood'),
  ('New Zealand', 'Nelson', 'Toi Toi'),
  ('New Zealand', 'Nelson', 'Wakatu'),
  ('New Zealand', 'Nelson', 'Washington Valley'),
  ('New Zealand', 'New Plymouth', 'Bell Block'),
  ('New Zealand', 'New Plymouth', 'Blagdon'),
  ('New Zealand', 'New Plymouth', 'Brooklands'),
  ('New Zealand', 'New Plymouth', 'Ferndale'),
  ('New Zealand', 'New Plymouth', 'Fitzroy'),
  ('New Zealand', 'New Plymouth', 'Frankleigh Park'),
  ('New Zealand', 'New Plymouth', 'Glen Avon'),
  ('New Zealand', 'New Plymouth', 'Highlands Park'),
  ('New Zealand', 'New Plymouth', 'Hurdon'),
  ('New Zealand', 'New Plymouth', 'Lower Vogeltown'),
  ('New Zealand', 'New Plymouth', 'Lynmouth'),
  ('New Zealand', 'New Plymouth', 'Marfell'),
  ('New Zealand', 'New Plymouth', 'Merrilands'),
  ('New Zealand', 'New Plymouth', 'Moturoa'),
  ('New Zealand', 'New Plymouth', 'New Plymouth'),
  ('New Zealand', 'New Plymouth', 'Port Taranaki'),
  ('New Zealand', 'New Plymouth', 'Ridgewood'),
  ('New Zealand', 'New Plymouth', 'Spotswood'),
  ('New Zealand', 'New Plymouth', 'Strandon'),
  ('New Zealand', 'New Plymouth', 'Upper Vogeltown'),
  ('New Zealand', 'New Plymouth', 'Vogeltown'),
  ('New Zealand', 'New Plymouth', 'Waiwhakaiho'),
  ('New Zealand', 'New Plymouth', 'Welbourn'),
  ('New Zealand', 'New Plymouth', 'Westown'),
  ('New Zealand', 'New Plymouth', 'Whalers Gate'),
  ('New Zealand', 'Ngaruawahia', 'Ngaruawahia'),
  ('New Zealand', 'Ngatea', 'Ngatea'),
  ('New Zealand', 'Ngatea', 'Turua'),
  ('New Zealand', 'Nightcaps', 'Nightcaps'),
  ('New Zealand', 'Oamaru', 'Ardgowan'),
  ('New Zealand', 'Oamaru', 'Holmes Hill'),
  ('New Zealand', 'Oamaru', 'Oamaru'),
  ('New Zealand', 'Oamaru', 'Oamaru North'),
  ('New Zealand', 'Oamaru', 'South Hill'),
  ('New Zealand', 'Oamaru', 'Waiareka Junction'),
  ('New Zealand', 'Oamaru', 'Weston'),
  ('New Zealand', 'Ohai', 'Ohai'),
  ('New Zealand', 'Ohakune', 'Ohakune'),
  ('New Zealand', 'Ongarue', 'Ongarue'),
  ('New Zealand', 'Opua', 'Opua'),
  ('New Zealand', 'Orewa', 'Hatfields Beach'),
  ('New Zealand', 'Orewa', 'Orewa'),
  ('New Zealand', 'Otautau', 'Otautau'),
  ('New Zealand', 'Otematata', 'Otematata'),
  ('New Zealand', 'Outram', 'Outram'),
  ('New Zealand', 'Owaka', 'Owaka'),
  ('New Zealand', 'Oxford', 'Oxford'),
  ('New Zealand', 'PaekÄkÄriki', 'Paekakariki'),
  ('New Zealand', 'Paeroa', 'Paeroa'),
  ('New Zealand', 'Pahiatua', 'Kaitawa'),
  ('New Zealand', 'Pahiatua', 'Makuri'),
  ('New Zealand', 'Pahiatua', 'Mangamutu'),
  ('New Zealand', 'Pahiatua', 'Mangatainoka'),
  ('New Zealand', 'Pahiatua', 'Pahiatua'),
  ('New Zealand', 'Paihia', 'Paihia'),
  ('New Zealand', 'Palmerston', 'Palmerston'),
  ('New Zealand', 'Palmerston North', 'Awapuni'),
  ('New Zealand', 'Palmerston North', 'Cloverlea'),
  ('New Zealand', 'Palmerston North', 'Fitzherbert'),
  ('New Zealand', 'Palmerston North', 'Highbury'),
  ('New Zealand', 'Palmerston North', 'Hokowhitu'),
  ('New Zealand', 'Palmerston North', 'Kelvin Grove'),
  ('New Zealand', 'Palmerston North', 'Linton'),
  ('New Zealand', 'Palmerston North', 'Milson'),
  ('New Zealand', 'Palmerston North', 'Palmerston North'),
  ('New Zealand', 'Palmerston North', 'Roslyn'),
  ('New Zealand', 'Palmerston North', 'Takaro'),
  ('New Zealand', 'Palmerston North', 'Terrace End'),
  ('New Zealand', 'Palmerston North', 'West End'),
  ('New Zealand', 'Palmerston North', 'Westbrook'),
  ('New Zealand', 'Palmerston North', 'Whakarongo'),
  ('New Zealand', 'Papakura', 'Opaheke'),
  ('New Zealand', 'Papakura', 'Pahurehure'),
  ('New Zealand', 'Papakura', 'Papakura'),
  ('New Zealand', 'Papakura', 'Red Hill'),
  ('New Zealand', 'Papakura', 'Rosehill'),
  ('New Zealand', 'Papamoa', 'Papamoa'),
  ('New Zealand', 'Papamoa', 'Papamoa Beach'),
  ('New Zealand', 'Paraparaumu', 'Maungakotukutuku'),
  ('New Zealand', 'Paraparaumu', 'Nikau Valley'),
  ('New Zealand', 'Paraparaumu', 'Otaihanga'),
  ('New Zealand', 'Paraparaumu', 'Paraparaumu'),
  ('New Zealand', 'Paraparaumu', 'Paraparaumu Beach'),
  ('New Zealand', 'Paraparaumu', 'Raumati Beach'),
  ('New Zealand', 'Paraparaumu', 'Raumati South'),
  ('New Zealand', 'Pareora', 'Pareora'),
  ('New Zealand', 'Picton', 'Picton'),
  ('New Zealand', 'Picton', 'Waikawa'),
  ('New Zealand', 'Piopio', 'Piopio'),
  ('New Zealand', 'Pirongia', 'Pirongia'),
  ('New Zealand', 'Pleasant Point', 'Pleasant Point'),
  ('New Zealand', 'Porirua', 'Aotea'),
  ('New Zealand', 'Porirua', 'Ascot Park'),
  ('New Zealand', 'Porirua', 'Camborne'),
  ('New Zealand', 'Porirua', 'Cannons Creek'),
  ('New Zealand', 'Porirua', 'Elsdon'),
  ('New Zealand', 'Porirua', 'Hongoeka'),
  ('New Zealand', 'Porirua', 'Kenepuru')
ON CONFLICT (city, area) DO NOTHING;

INSERT INTO service_areas (country, city, area) VALUES
  ('New Zealand', 'Porirua', 'Papakowhai'),
  ('New Zealand', 'Porirua', 'Paremata'),
  ('New Zealand', 'Porirua', 'Plimmerton'),
  ('New Zealand', 'Porirua', 'Porirua City Centre'),
  ('New Zealand', 'Porirua', 'Pukerua Bay'),
  ('New Zealand', 'Porirua', 'Ranui'),
  ('New Zealand', 'Porirua', 'Takapuwahia'),
  ('New Zealand', 'Porirua', 'Titahi Bay'),
  ('New Zealand', 'Porirua', 'Waitangirua'),
  ('New Zealand', 'Porirua', 'Whitby'),
  ('New Zealand', 'Prebbleton', 'Prebbleton'),
  ('New Zealand', 'Puhi Puhi', 'Puhi Puhi'),
  ('New Zealand', 'Pukekohe', 'Pukekohe'),
  ('New Zealand', 'PutÄruru', 'Putaruru'),
  ('New Zealand', 'PÄtea', 'Patea'),
  ('New Zealand', 'Queenstown', 'Fernhill'),
  ('New Zealand', 'Queenstown', 'Frankton'),
  ('New Zealand', 'Queenstown', 'Kelvin Heights'),
  ('New Zealand', 'Queenstown', 'Queenstown'),
  ('New Zealand', 'Queenstown', 'Sunshine Bay'),
  ('New Zealand', 'Raetihi', 'Makakahi'),
  ('New Zealand', 'Raetihi', 'Raetihi'),
  ('New Zealand', 'Raglan', 'Raglan'),
  ('New Zealand', 'Rakaia', 'Rakaia'),
  ('New Zealand', 'Ranfurly', 'Ranfurly'),
  ('New Zealand', 'Rangiora', 'Fernside'),
  ('New Zealand', 'Rangiora', 'Rangiora'),
  ('New Zealand', 'Reefton', 'Reefton'),
  ('New Zealand', 'Renwick', 'Renwick'),
  ('New Zealand', 'Richmond', 'Hope'),
  ('New Zealand', 'Richmond', 'Richmond'),
  ('New Zealand', 'Riverhead', 'Riverhead'),
  ('New Zealand', 'Riverton/Aparima', 'Longwood'),
  ('New Zealand', 'Riverton/Aparima', 'Riverton/Aparima'),
  ('New Zealand', 'Rolleston', 'Rolleston'),
  ('New Zealand', 'Ross', 'Ross'),
  ('New Zealand', 'Rotorua', 'Fairy Springs'),
  ('New Zealand', 'Rotorua', 'Fenton Park'),
  ('New Zealand', 'Rotorua', 'Fordlands'),
  ('New Zealand', 'Rotorua', 'Glenholme'),
  ('New Zealand', 'Rotorua', 'Hannahs Bay'),
  ('New Zealand', 'Rotorua', 'Hillcrest'),
  ('New Zealand', 'Rotorua', 'Holdens Bay'),
  ('New Zealand', 'Rotorua', 'Kawaha Point'),
  ('New Zealand', 'Rotorua', 'Koutu'),
  ('New Zealand', 'Rotorua', 'Lake Okareka'),
  ('New Zealand', 'Rotorua', 'Lake Tarawera'),
  ('New Zealand', 'Rotorua', 'Lynmore'),
  ('New Zealand', 'Rotorua', 'Mangakakahi'),
  ('New Zealand', 'Rotorua', 'Matipo Heights'),
  ('New Zealand', 'Rotorua', 'Mourea'),
  ('New Zealand', 'Rotorua', 'Ngapuna'),
  ('New Zealand', 'Rotorua', 'Ngongotaha'),
  ('New Zealand', 'Rotorua', 'Ohinemutu'),
  ('New Zealand', 'Rotorua', 'Owhata'),
  ('New Zealand', 'Rotorua', 'Pomare'),
  ('New Zealand', 'Rotorua', 'Pukehangi'),
  ('New Zealand', 'Rotorua', 'Rotorua'),
  ('New Zealand', 'Rotorua', 'Selwyn Heights'),
  ('New Zealand', 'Rotorua', 'Springfield'),
  ('New Zealand', 'Rotorua', 'Sunnybrook'),
  ('New Zealand', 'Rotorua', 'Tihiotonga'),
  ('New Zealand', 'Rotorua', 'Tikitere'),
  ('New Zealand', 'Rotorua', 'Utuhina'),
  ('New Zealand', 'Rotorua', 'Victoria'),
  ('New Zealand', 'Rotorua', 'Western Heights'),
  ('New Zealand', 'Rotorua', 'Whakarewarewa'),
  ('New Zealand', 'Roxburgh', 'Roxburgh'),
  ('New Zealand', 'RuakÄkÄ', 'Ruakaka'),
  ('New Zealand', 'Ruatoria', 'Ruatoria'),
  ('New Zealand', 'Ruawai', 'Ruawai'),
  ('New Zealand', 'Runanga', 'Dunollie'),
  ('New Zealand', 'Runanga', 'Runanga'),
  ('New Zealand', 'Russell', 'Okiato'),
  ('New Zealand', 'Russell', 'Russell'),
  ('New Zealand', 'Sanson', 'Sanson'),
  ('New Zealand', 'Seaward Valley', 'Seaward Valley'),
  ('New Zealand', 'Seddon', 'Seddon'),
  ('New Zealand', 'Shannon', 'Shannon'),
  ('New Zealand', 'Silverdale', 'Silverdale'),
  ('New Zealand', 'Snells Beach', 'Snells Beach'),
  ('New Zealand', 'Southbridge', 'Southbridge'),
  ('New Zealand', 'Spring Creek', 'Spring Creek'),
  ('New Zealand', 'Springston', 'Springston'),
  ('New Zealand', 'Stewart Island', 'Halfmoon Bay / Oban'),
  ('New Zealand', 'Stirling', 'Stirling'),
  ('New Zealand', 'Stratford', 'Stratford'),
  ('New Zealand', 'Taihape', 'Taihape'),
  ('New Zealand', 'Taihape', 'Utiku'),
  ('New Zealand', 'Taipa', 'Taipa'),
  ('New Zealand', 'Tairua', 'Tairua'),
  ('New Zealand', 'Takanini', 'Conifer Grove'),
  ('New Zealand', 'Takapau', 'Takapau'),
  ('New Zealand', 'Tangimoana', 'Parewanui'),
  ('New Zealand', 'Tangimoana', 'Tangimoana'),
  ('New Zealand', 'Tapanui', 'Tapanui'),
  ('New Zealand', 'Taumarunui', 'Aukopae'),
  ('New Zealand', 'Taumarunui', 'Hikumutu'),
  ('New Zealand', 'Taumarunui', 'Kirikau'),
  ('New Zealand', 'Taumarunui', 'Manunui'),
  ('New Zealand', 'Taumarunui', 'Taumarunui'),
  ('New Zealand', 'Taupiri', 'Taupiri'),
  ('New Zealand', 'TaupÅ', 'Acacia Bay'),
  ('New Zealand', 'TaupÅ', 'Hilltop'),
  ('New Zealand', 'TaupÅ', 'Maunganamu'),
  ('New Zealand', 'TaupÅ', 'Nukuhau'),
  ('New Zealand', 'TaupÅ', 'Rainbow Point'),
  ('New Zealand', 'TaupÅ', 'Rangatira Park'),
  ('New Zealand', 'TaupÅ', 'Richmond Heights'),
  ('New Zealand', 'TaupÅ', 'Tauhara'),
  ('New Zealand', 'TaupÅ', 'Taupo'),
  ('New Zealand', 'TaupÅ', 'Two Mile Bay'),
  ('New Zealand', 'TaupÅ', 'Waipahihi'),
  ('New Zealand', 'TaupÅ', 'Wairakei'),
  ('New Zealand', 'TaupÅ', 'Wharewaka'),
  ('New Zealand', 'Tauranga', 'Bellevue'),
  ('New Zealand', 'Tauranga', 'Bethlehem'),
  ('New Zealand', 'Tauranga', 'Brookfield'),
  ('New Zealand', 'Tauranga', 'Gate Pa'),
  ('New Zealand', 'Tauranga', 'Greerton'),
  ('New Zealand', 'Tauranga', 'Hairini'),
  ('New Zealand', 'Tauranga', 'Judea'),
  ('New Zealand', 'Tauranga', 'Matua'),
  ('New Zealand', 'Tauranga', 'Maungatapu'),
  ('New Zealand', 'Tauranga', 'Otumoetai'),
  ('New Zealand', 'Tauranga', 'Parkvale'),
  ('New Zealand', 'Tauranga', 'Poike'),
  ('New Zealand', 'Tauranga', 'Pyes Pa'),
  ('New Zealand', 'Tauranga', 'Tauranga'),
  ('New Zealand', 'Tauranga', 'Tauranga South'),
  ('New Zealand', 'Tauranga', 'Tauriko'),
  ('New Zealand', 'Tauranga', 'Welcome Bay'),
  ('New Zealand', 'Te Anau', 'Te Anau'),
  ('New Zealand', 'Te Aroha', 'Te Aroha'),
  ('New Zealand', 'Te Awamutu', 'Kihikihi'),
  ('New Zealand', 'Te Awamutu', 'Te Awamutu'),
  ('New Zealand', 'Te Awanga', 'Te Awanga'),
  ('New Zealand', 'Te Karaka', 'Te Karaka'),
  ('New Zealand', 'Te Kauwhata', 'Te Kauwhata'),
  ('New Zealand', 'Te KÅ«iti', 'Te Kuiti'),
  ('New Zealand', 'Te Puke', 'Te Puke'),
  ('New Zealand', 'Temuka', 'Temuka'),
  ('New Zealand', 'Thames', 'Thames'),
  ('New Zealand', 'The Pines Beach', 'The Pines Beach'),
  ('New Zealand', 'Timaru', 'Gleniti'),
  ('New Zealand', 'Timaru', 'Glenwood'),
  ('New Zealand', 'Timaru', 'Highfield'),
  ('New Zealand', 'Timaru', 'Kensington'),
  ('New Zealand', 'Timaru', 'Maori Hill'),
  ('New Zealand', 'Timaru', 'Marchwiel'),
  ('New Zealand', 'Timaru', 'Oceanview'),
  ('New Zealand', 'Timaru', 'Parkside'),
  ('New Zealand', 'Timaru', 'Redruth'),
  ('New Zealand', 'Timaru', 'Seaview'),
  ('New Zealand', 'Timaru', 'Smithfield'),
  ('New Zealand', 'Timaru', 'Timaru'),
  ('New Zealand', 'Timaru', 'Timaru Port'),
  ('New Zealand', 'Timaru', 'Waimataitai'),
  ('New Zealand', 'Timaru', 'Washdyke'),
  ('New Zealand', 'Timaru', 'Watlington'),
  ('New Zealand', 'Timaru', 'West End'),
  ('New Zealand', 'Tokoroa', 'Tokoroa'),
  ('New Zealand', 'Tuakau', 'Tuakau'),
  ('New Zealand', 'Tuatapere', 'Tuatapere'),
  ('New Zealand', 'Twizel', 'Twizel'),
  ('New Zealand', 'TÄkaka', 'Takaka'),
  ('New Zealand', 'TÄneatua', 'Taneatua'),
  ('New Zealand', 'TÄ«rau', 'Okoroire'),
  ('New Zealand', 'TÄ«rau', 'Tirau'),
  ('New Zealand', 'TÅ«rangi', 'Turangi'),
  ('New Zealand', 'TÅ«rangi', 'Waiotaka Valley'),
  ('New Zealand', 'Upper Hutt', 'Akatarawa'),
  ('New Zealand', 'Upper Hutt', 'Akatarawa Valley'),
  ('New Zealand', 'Upper Hutt', 'Birchville'),
  ('New Zealand', 'Upper Hutt', 'Brown Owl'),
  ('New Zealand', 'Upper Hutt', 'Clouston Park'),
  ('New Zealand', 'Upper Hutt', 'Craigs Flat'),
  ('New Zealand', 'Upper Hutt', 'Ebdentown'),
  ('New Zealand', 'Upper Hutt', 'Elderslea'),
  ('New Zealand', 'Upper Hutt', 'Heretaunga'),
  ('New Zealand', 'Upper Hutt', 'Kaitoke'),
  ('New Zealand', 'Upper Hutt', 'Kingsley Heights'),
  ('New Zealand', 'Upper Hutt', 'Maidstone'),
  ('New Zealand', 'Upper Hutt', 'Mangaroa'),
  ('New Zealand', 'Upper Hutt', 'Maoribank'),
  ('New Zealand', 'Upper Hutt', 'Maymorn'),
  ('New Zealand', 'Upper Hutt', 'Pinehaven'),
  ('New Zealand', 'Upper Hutt', 'Riverstone Terraces'),
  ('New Zealand', 'Upper Hutt', 'Silverstream'),
  ('New Zealand', 'Upper Hutt', 'Te Marua'),
  ('New Zealand', 'Upper Hutt', 'Timberlea'),
  ('New Zealand', 'Upper Hutt', 'Totara Park'),
  ('New Zealand', 'Upper Hutt', 'Trentham'),
  ('New Zealand', 'Upper Hutt', 'Upper Hutt Central'),
  ('New Zealand', 'Upper Hutt', 'Wallaceville'),
  ('New Zealand', 'Waddington', 'Waddington'),
  ('New Zealand', 'Waharoa', 'Waharoa'),
  ('New Zealand', 'Waiau', 'Waiau'),
  ('New Zealand', 'Waiheke Island', 'Omiha'),
  ('New Zealand', 'Waiheke Island', 'Oneroa')
ON CONFLICT (city, area) DO NOTHING;

INSERT INTO service_areas (country, city, area) VALUES
  ('New Zealand', 'Waiheke Island', 'Onetangi'),
  ('New Zealand', 'Waiheke Island', 'Ostend'),
  ('New Zealand', 'Waiheke Island', 'Palm Beach'),
  ('New Zealand', 'Waiheke Island', 'Surfdale'),
  ('New Zealand', 'Waihi', 'Waihi'),
  ('New Zealand', 'Waihi', 'Waikino'),
  ('New Zealand', 'Waihi Beach', 'Athenree'),
  ('New Zealand', 'Waihi Beach', 'Bowentown'),
  ('New Zealand', 'Waihi Beach', 'Waihi Beach'),
  ('New Zealand', 'Waikanae', 'Waikanae'),
  ('New Zealand', 'Waikanae', 'Waikanae Beach'),
  ('New Zealand', 'Waikari', 'Waikari'),
  ('New Zealand', 'Waikouaiti', 'Waikouaiti'),
  ('New Zealand', 'Waikuku Beach', 'Waikuku Beach'),
  ('New Zealand', 'Waimate', 'Waimate'),
  ('New Zealand', 'Waimauku', 'Waimauku'),
  ('New Zealand', 'Waiouru', 'Waiouru'),
  ('New Zealand', 'Waipawa', 'Waipawa'),
  ('New Zealand', 'Waipu', 'Waipu'),
  ('New Zealand', 'Waipukurau', 'Waipukurau'),
  ('New Zealand', 'Wairoa', 'Wairoa'),
  ('New Zealand', 'Waitara', 'Waitara'),
  ('New Zealand', 'Waitoa', 'Waitoa'),
  ('New Zealand', 'Waiuku', 'Waiuku'),
  ('New Zealand', 'Wakefield', 'Pigeon Valley'),
  ('New Zealand', 'Wakefield', 'Wakefield'),
  ('New Zealand', 'Wallacetown', 'Wallacetown'),
  ('New Zealand', 'Warkworth', 'Warkworth'),
  ('New Zealand', 'Waverley', 'Waverley'),
  ('New Zealand', 'Wellington', 'Aro Valley'),
  ('New Zealand', 'Wellington', 'Berhampore'),
  ('New Zealand', 'Wellington', 'Breaker Bay'),
  ('New Zealand', 'Wellington', 'Broadmeadows'),
  ('New Zealand', 'Wellington', 'Brooklyn'),
  ('New Zealand', 'Wellington', 'Churton Park'),
  ('New Zealand', 'Wellington', 'Crofton Downs'),
  ('New Zealand', 'Wellington', 'Glenside'),
  ('New Zealand', 'Wellington', 'Grenada North'),
  ('New Zealand', 'Wellington', 'Grenada Village'),
  ('New Zealand', 'Wellington', 'Hataitai'),
  ('New Zealand', 'Wellington', 'Highbury'),
  ('New Zealand', 'Wellington', 'Horokiwi'),
  ('New Zealand', 'Wellington', 'Houghton Bay'),
  ('New Zealand', 'Wellington', 'Island Bay'),
  ('New Zealand', 'Wellington', 'Johnsonville'),
  ('New Zealand', 'Wellington', 'Kaiwharawhara'),
  ('New Zealand', 'Wellington', 'Karaka Bays'),
  ('New Zealand', 'Wellington', 'Karori'),
  ('New Zealand', 'Wellington', 'Kelburn'),
  ('New Zealand', 'Wellington', 'Khandallah'),
  ('New Zealand', 'Wellington', 'Kilbirnie'),
  ('New Zealand', 'Wellington', 'Kingston'),
  ('New Zealand', 'Wellington', 'Lyall Bay'),
  ('New Zealand', 'Wellington', 'Makara'),
  ('New Zealand', 'Wellington', 'Maupuia'),
  ('New Zealand', 'Wellington', 'Melrose'),
  ('New Zealand', 'Wellington', 'Miramar'),
  ('New Zealand', 'Wellington', 'Moa Point'),
  ('New Zealand', 'Wellington', 'Mornington'),
  ('New Zealand', 'Wellington', 'Mount Cook'),
  ('New Zealand', 'Wellington', 'Mount Victoria'),
  ('New Zealand', 'Wellington', 'Newlands'),
  ('New Zealand', 'Wellington', 'Newtown'),
  ('New Zealand', 'Wellington', 'Ngaio'),
  ('New Zealand', 'Wellington', 'Ngauranga'),
  ('New Zealand', 'Wellington', 'Northland'),
  ('New Zealand', 'Wellington', 'Ohariu'),
  ('New Zealand', 'Wellington', 'Oriental Bay'),
  ('New Zealand', 'Wellington', 'Owhiro Bay'),
  ('New Zealand', 'Wellington', 'Paparangi'),
  ('New Zealand', 'Wellington', 'Pipitea'),
  ('New Zealand', 'Wellington', 'Rongotai'),
  ('New Zealand', 'Wellington', 'Roseneath'),
  ('New Zealand', 'Wellington', 'Seatoun'),
  ('New Zealand', 'Wellington', 'Southgate'),
  ('New Zealand', 'Wellington', 'Strathmore Park'),
  ('New Zealand', 'Wellington', 'Takapu Valley'),
  ('New Zealand', 'Wellington', 'Tawa'),
  ('New Zealand', 'Wellington', 'Te Aro'),
  ('New Zealand', 'Wellington', 'Thorndon'),
  ('New Zealand', 'Wellington', 'Vogeltown'),
  ('New Zealand', 'Wellington', 'Wadestown'),
  ('New Zealand', 'Wellington', 'Wellington Central'),
  ('New Zealand', 'Wellington', 'Wilton'),
  ('New Zealand', 'Wellington', 'Woodridge'),
  ('New Zealand', 'Wellsford', 'Wellsford'),
  ('New Zealand', 'Westport', 'Carters Beach'),
  ('New Zealand', 'Westport', 'Westport'),
  ('New Zealand', 'WhakatÄne', 'Coastlands'),
  ('New Zealand', 'WhakatÄne', 'Maraetotara'),
  ('New Zealand', 'WhakatÄne', 'Poroporo'),
  ('New Zealand', 'WhakatÄne', 'Whakatane'),
  ('New Zealand', 'WhangamatÄ', 'Whangamata'),
  ('New Zealand', 'Whanganui', 'Aramoho'),
  ('New Zealand', 'Whanganui', 'Bastia Hill'),
  ('New Zealand', 'Whanganui', 'Castlecliff'),
  ('New Zealand', 'Whanganui', 'College Estate'),
  ('New Zealand', 'Whanganui', 'Durie Hill'),
  ('New Zealand', 'Whanganui', 'Gonville'),
  ('New Zealand', 'Whanganui', 'Okoia'),
  ('New Zealand', 'Whanganui', 'Otamatea'),
  ('New Zealand', 'Whanganui', 'Papaiti'),
  ('New Zealand', 'Whanganui', 'Putiki'),
  ('New Zealand', 'Whanganui', 'Saint Johns Hill'),
  ('New Zealand', 'Whanganui', 'Springvale'),
  ('New Zealand', 'Whanganui', 'Tawhero'),
  ('New Zealand', 'Whanganui', 'Westmere'),
  ('New Zealand', 'Whanganui', 'Whanganui'),
  ('New Zealand', 'Whanganui', 'Whanganui Airport'),
  ('New Zealand', 'Whanganui', 'Whanganui East'),
  ('New Zealand', 'WhangaparÄoa', 'Arkles Bay'),
  ('New Zealand', 'WhangaparÄoa', 'Army Bay'),
  ('New Zealand', 'WhangaparÄoa', 'Gulf Harbour'),
  ('New Zealand', 'WhangaparÄoa', 'Manly'),
  ('New Zealand', 'WhangaparÄoa', 'Matakatia'),
  ('New Zealand', 'WhangaparÄoa', 'Red Beach'),
  ('New Zealand', 'WhangaparÄoa', 'Stanmore Bay'),
  ('New Zealand', 'WhangaparÄoa', 'Tindalls Beach'),
  ('New Zealand', 'WhangaparÄoa', 'Wade Heads'),
  ('New Zealand', 'Whangateau', 'Whangateau'),
  ('New Zealand', 'WhangÄrei', 'Abbey Caves'),
  ('New Zealand', 'WhangÄrei', 'Avenues'),
  ('New Zealand', 'WhangÄrei', 'Horahora'),
  ('New Zealand', 'WhangÄrei', 'Kensington'),
  ('New Zealand', 'WhangÄrei', 'Mangapai'),
  ('New Zealand', 'WhangÄrei', 'Marsden Point'),
  ('New Zealand', 'WhangÄrei', 'Mata'),
  ('New Zealand', 'WhangÄrei', 'Maunu'),
  ('New Zealand', 'WhangÄrei', 'Morningside'),
  ('New Zealand', 'WhangÄrei', 'Oakleigh'),
  ('New Zealand', 'WhangÄrei', 'One Tree Point'),
  ('New Zealand', 'WhangÄrei', 'Onerahi'),
  ('New Zealand', 'WhangÄrei', 'Otaika'),
  ('New Zealand', 'WhangÄrei', 'Otangarei'),
  ('New Zealand', 'WhangÄrei', 'Parahaki'),
  ('New Zealand', 'WhangÄrei', 'Port Whangarei'),
  ('New Zealand', 'WhangÄrei', 'Portland'),
  ('New Zealand', 'WhangÄrei', 'Pukenui Forest'),
  ('New Zealand', 'WhangÄrei', 'Puwera'),
  ('New Zealand', 'WhangÄrei', 'Raumanga'),
  ('New Zealand', 'WhangÄrei', 'Regent'),
  ('New Zealand', 'WhangÄrei', 'Riverside'),
  ('New Zealand', 'WhangÄrei', 'Springfield'),
  ('New Zealand', 'WhangÄrei', 'Takahiwai'),
  ('New Zealand', 'WhangÄrei', 'Te Kamo'),
  ('New Zealand', 'WhangÄrei', 'Tikipunga'),
  ('New Zealand', 'WhangÄrei', 'Whangarei'),
  ('New Zealand', 'WhangÄrei', 'Whangarei Airport'),
  ('New Zealand', 'WhangÄrei', 'Whau Valley'),
  ('New Zealand', 'WhangÄrei', 'Woodhill'),
  ('New Zealand', 'Whirinaki', 'Whirinaki'),
  ('New Zealand', 'Whitianga', 'Whitianga'),
  ('New Zealand', 'Winchester', 'Winchester'),
  ('New Zealand', 'Winton', 'Winton'),
  ('New Zealand', 'Woodend', 'Woodend'),
  ('New Zealand', 'Woodend', 'Woodend Beach'),
  ('New Zealand', 'Woodville', 'Woodville'),
  ('New Zealand', 'Wyndham', 'Wyndham'),
  ('New Zealand', 'Wanaka', 'Wanaka'),
  ('New Zealand', 'Oakura', 'Oakura'),
  ('New Zealand', 'Ohaupo', 'Ohaupo'),
  ('New Zealand', 'Ohope', 'Ohope'),
  ('New Zealand', 'Ohura', 'Ohura'),
  ('New Zealand', 'Okato', 'Okato'),
  ('New Zealand', 'Omarama', 'Omarama'),
  ('New Zealand', 'Omokoroa', 'Omokoroa'),
  ('New Zealand', 'Opunake', 'Opunake'),
  ('New Zealand', 'Opotiki', 'Opotiki'),
  ('New Zealand', 'Opotiki', 'Waiotahe'),
  ('New Zealand', 'Otaki', 'Otaki'),
  ('New Zealand', 'Otaki', 'Otaki Beach'),
  ('New Zealand', 'Otorohanga', 'Otorohanga'),
  ('New Zealand', 'Otane', 'Otane')
ON CONFLICT (city, area) DO NOTHING;
